#!/usr/bin/env -S bash ../.port_include.sh
port='libxml2'
version='2.15.1'
files=(
    "https://download.gnome.org/sources/libxml2/2.15/libxml2-${version}.tar.xz#c008bac08fd5c7b4a87f7b8a71f283fa581d80d80ff8d2efd3b26224c39bc54c"
)
useconfigure='true'
use_fresh_config_sub='true'
configopts=(
    "--with-sysroot=${SERENITY_INSTALL_ROOT}"
    '--prefix=/usr/local'
    '--without-python'
    '--disable-static'
    '--enable-shared'
)
depends=(
    'libiconv'
    'xz'
)
